HF_TOKEN = "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"
GROQ_API_KEY = "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"
TAVILY_API_KEY = "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"
SERPER_API_KEY = "1cc153e6a90b4700c5f617497d62933ace7b17e2"